import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { repairLegacyIdentities } from '../../src/core/legacy-identities';
import { legacyCommandReceiptContent } from '../../src/core/receipt-content';
import { validateProject } from '../../src/core/model';
import type { Clip, Keyframe, Project, Track } from '../../src/core/model';

type LegacyClip = Omit<Clip, 'keyframes'> & {
  keyframes: Partial<
    Record<keyof Clip['keyframes'], (Omit<Keyframe, 'id'> & { id?: string })[]>
  >;
};
type LegacyProject = Omit<Project, 'tracks'> & {
  tracks: (Omit<Track, 'clips'> & { clips: LegacyClip[] })[];
};
interface LegacyFixture {
  provenance: { commit: string; moduleSha256: Record<string, string> };
  requests: Record<
    string,
    {
      input: { expectedRevision: number };
      saved: { content: string; receipt: { appliedRevision: number } };
    }
  >;
  states: Record<string, LegacyProject>;
  record: {
    project: LegacyProject;
    undo: LegacyProject[];
    redo: LegacyProject[];
  };
}

// This committed fixture was generated by executing the actual Store and core
// modules from 984107dbf63dc95cc72f980b65bfaae6e86bc727 with Vite SSR, not by
// current compatibility helpers. A clone-on-read in-memory IDB adapter recorded
// base Store.create/apply/history results. The fixture carries source hashes.
const fixture = JSON.parse(
  readFileSync(new URL('../fixtures/legacy-v1.json', import.meta.url), 'utf8'),
) as LegacyFixture;

function chronologicalProjects() {
  return [
    ...fixture.record.undo,
    fixture.record.project,
    ...[...fixture.record.redo].reverse(),
  ];
}

function cueIds(project: LegacyProject | Project, clipId: string) {
  return project.tracks
    .flatMap((track) => track.clips)
    .find((clip) => clip.id === clipId)
    ?.cues.map((cue) => cue.id);
}

function withoutNestedIds(project: LegacyProject | Project) {
  const omitId = <T extends { id?: string }>(value: T) => {
    const copy = { ...value };
    delete copy.id;
    return copy;
  };
  return {
    ...project,
    tracks: project.tracks.map((track) => ({
      ...track,
      clips: track.clips.map((clip) => ({
        ...clip,
        cues: clip.cues.map(omitId),
        keyframes: Object.fromEntries(
          Object.entries(clip.keyframes).map(([name, keys]) => [
            name,
            keys?.map(omitId),
          ]),
        ),
      })),
    })),
  };
}

describe('deployed version-one identity compatibility', () => {
  it('retains authentic base duplicate IDs and receipt normalization in the fixture', () => {
    expect(fixture.provenance.commit).toBe(
      '984107dbf63dc95cc72f980b65bfaae6e86bc727',
    );
    expect(Object.keys(fixture.provenance.moduleSha256)).toHaveLength(5);
    expect(
      Object.values(fixture.provenance.moduleSha256).every((hash) =>
        /^[a-f0-9]{64}$/.test(hash),
      ),
    ).toBe(true);
    const duplicate = fixture.states.duplicateClip!;
    expect(cueIds(duplicate, 'original-caption')).toEqual([
      'sentence-a',
      'sentence-b',
    ]);
    expect(cueIds(duplicate, 'duplicate-caption')).toEqual(
      cueIds(duplicate, 'original-caption'),
    );
    expect(
      duplicate.tracks
        .flatMap((track) => track.clips)
        .flatMap((clip) => Object.values(clip.keyframes).flat())
        .every((key) => key?.id === undefined),
    ).toBe(true);
    for (const request of Object.values(fixture.requests)) {
      expect(legacyCommandReceiptContent(request.input)).toBe(
        request.saved.content,
      );
      expect(request.saved.receipt.appliedRevision).toBe(
        request.input.expectedRevision + 1,
      );
    }
  });

  it('preserves the original cue owner across current, undo and reordered redo states', () => {
    const projects = chronologicalProjects();
    const before = structuredClone(projects);
    const repaired = repairLegacyIdentities(projects);
    const originalIds = ['sentence-a', 'sentence-b'];
    let duplicateIds: string[] | undefined;
    for (const project of repaired) {
      const original = cueIds(project, 'original-caption');
      if (original) expect(original).toEqual(originalIds);
      const duplicate = cueIds(project, 'duplicate-caption');
      if (duplicate) {
        duplicateIds ??= duplicate;
        expect(duplicate).toEqual(duplicateIds);
        expect(duplicate).not.toEqual(originalIds);
        expect(duplicate.every((id) => id.startsWith('cue-'))).toBe(true);
      }
      expect(validateProject(project)).toEqual(project);
    }
    expect(duplicateIds).toHaveLength(2);
    expect(new Set(duplicateIds).size).toBe(2);
    expect(repaired.at(-1)!.tracks.map((track) => track.id)).toEqual([
      'copied-captions',
      'captions',
    ]);
    expect(projects).toEqual(before);
  });

  it('keeps owner identities constant when later snapshots change track order', () => {
    const projects = chronologicalProjects();
    const expected = repairLegacyIdentities(projects);
    const reordered = repairLegacyIdentities(
      projects.map((project) => ({
        ...project,
        tracks: [...project.tracks].reverse(),
      })),
    );
    for (let index = 0; index < expected.length; index++)
      for (const clipId of ['original-caption', 'duplicate-caption'])
        expect(cueIds(reordered[index]!, clipId)).toEqual(
          cueIds(expected[index]!, clipId),
        );
    expect(repairLegacyIdentities(expected)).toEqual(expected);
  });

  it('changes only nested identities while preserving timing, settings and revisions', () => {
    const projects = chronologicalProjects();
    const repaired = repairLegacyIdentities(projects);
    expect(repaired.map(withoutNestedIds)).toEqual(
      projects.map(withoutNestedIds),
    );
    expect(repaired.map((project) => project.revision)).toEqual([
      0, 1, 2, 3, 4, 7, 6,
    ]);
    const identities = new Map<string, string>();
    for (const project of repaired)
      for (const track of project.tracks)
        for (const clip of track.clips)
          for (const [parameter, keys] of Object.entries(clip.keyframes))
            for (const key of keys) {
              const owner = `${clip.id}:${parameter}:${key.timeUs}`;
              if (identities.has(owner))
                expect(key.id).toBe(identities.get(owner));
              else identities.set(owner, key.id);
            }
    expect(identities.size).toBeGreaterThan(0);
  });

  it('rejects repeated cue IDs within the same clip', () => {
    const project = structuredClone(fixture.states.beforeDuplicate!);
    const clip = project.tracks[0]!.clips[0]!;
    clip.cues[1]!.id = clip.cues[0]!.id;
    expect(() => repairLegacyIdentities([project])).toThrow(
      'Legacy cue ID collides',
    );
  });

  it.each(['project', 'track', 'clip', 'keyframe'] as const)(
    'rejects a cue ID collision with a %s',
    (kind) => {
      const project = structuredClone(fixture.states.beforeDuplicate!);
      const clip = project.tracks[0]!.clips[0]!;
      const cueId = clip.cues[0]!.id;
      if (kind === 'project') project.id = cueId;
      else if (kind === 'track') project.tracks[0]!.id = cueId;
      else if (kind === 'clip') clip.id = cueId;
      else clip.keyframes.opacity![0]!.id = cueId;
      expect(() => repairLegacyIdentities([project])).toThrow(
        'Legacy cue ID collides',
      );
    },
  );

  it('rejects unknown document versions and fields instead of repairing them', () => {
    const project = fixture.states.beforeDuplicate!;
    expect(() =>
      repairLegacyIdentities([{ ...project, schemaVersion: 2 }]),
    ).toThrow();
    expect(() =>
      repairLegacyIdentities([{ ...project, unknown: true }]),
    ).toThrow();
  });
});
